[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F446RE"

rustflags = [
  "-C", "link-arg=-nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "debug"
DEFMT_RTT_BUFFER_SIZE = "1024"